### ISSUE TITLE
some info gone

### ISSUE THREAD

**Issue by NoCodeBugsFree** [UnrealisticDev/Renom#10]
hi, nice tool, thanks! Relatively easy do rename of huge project.
but some info gone from my project.
for example DefaultGame.ini file contains 
Homepage="https://Mygame.game" becomes Homepage=https://Mygame.game ( no quotes ) 
and this cause https://i.imgur.com/gtgGFK2.png missing info in editor.
thank you very much!

**Comment by msmoiz** [comment]
Thanks for sharing this issue. Can you provide more information about the bug? What operating system are you using? Are you trying to rename a sample project like Lyra or ShooterGame or is this built from scratch? Does it contain code or Blueprints only?

**Comment by msmoiz** [comment]
This was caused by a missing flag in the underlying ini config parser. Please reopen this if the issue persists after upgrading to the latest version (1.1.2).
