### ISSUE TITLE
Put it on itch.io

### ISSUE THREAD

**Issue by BialySztorm** [UnrealisticDev/Renom#12]
Put on itch.io, so it can be automatically updated, easier to manage.
If you want to I can pass you python script for publishing with versioning

**Comment by msmoiz** [comment]
Itch.io is more focused on hosting games, so I am not sure it would be a good match for this tool, though perhaps it would be useful to upload it to `winget` or another package manager. In either event, I would like to see more interest in this feature before considering it further.

**Comment by BialySztorm** [comment]
well, there is section on itch for tools, so you can just post it as tool, but really don't know why your tool is not a standard yet
