### ISSUE TITLE
Unable to change the folder name - Throws Error

### ISSUE THREAD

**Issue by 980Mohid** [UnrealisticDev/Renom#2]
I get an error saying that it was not able to rename the root folder because of OS restrictions. I've tried running the script as Admin but still the same issue

**Comment by msmoiz** [comment]
Can you share more information about the OS you are seeing the error on, the exact error message, and the file permissions you have on the folder?

**Comment by msmoiz** [comment]
This is the final step in the process, but if any step fails the process will roll back.

**Comment by msmoiz** [comment]
Can you share the full output logs, as well as system specs (OS version, etc.)?

**Comment by msmoiz** [comment]
Cannot reproduce without further detail; please reopen with more information.
