### ISSUE TITLE
[ error ]          The specified file cannot be found. (os error 2)

### ISSUE THREAD

**Issue by SadBlackFox** [UnrealisticDev/Renom#5]
![This is an image](https://dl.dropboxusercontent.com/s/wcqvh1vs1dh8mhl/renom_paxEDT9yRd.png)
![This is an image](https://dl.dropboxusercontent.com/s/svtckbc8ketk29g/UE4Editor_H2C9duFyCP.png)
@msmoiz  Where are the logs stored?

**Comment by msmoiz** [comment]
The logs are not stored anywhere at the moment. However, you can always redirect the the output to log from the command line:


```
renom > logs.txt
```

**Comment by SadBlackFox** [comment]
I wanted to know which file is "Not Found" because the specific problematic file, line, etc. is not listed on the command line.

**Comment by msmoiz** [comment]
The error corresponds to the preceding change. In this case, that means *MultiplayerShooter.h* is missing at the specified path. To fix this, you can either move that file to the expected path (the program expects a very specific file structure), or make the changes manually.

**Comment by msmoiz** [comment]
This issue has been resolved with the latest release (0.1.5). The tool no longer looks for the module header file (since this can technically remain the same) and instead hunts for the module implementation file (where the `IMPLEMENT_MODULE` macro is called) in the module source tree.
