### ISSUE TITLE
Request Renom for UE5.1

### ISSUE THREAD

**Issue by HongPong** [UnrealisticDev/Renom#7]
Thanks so much for this program. The same types of problems with renaming projects persist in Unreal Engine 5.1 so I would request having that update. Thank you!

**Comment by msmoiz** [comment]
The README is a bit out of date, but the tool should work for Unreal Engine 5 as well. I'll make a note to update the README. Or is there a specific issue with Unreal Engine 5.1 that you are seeing?

**Comment by HongPong** [comment]
Ah thank you, I had not tried yet and didn't want to break anything in
testing it. Best regards!
