### ISSUE TITLE
Is it possible to batch rename many plugins

### ISSUE THREAD

**Issue by ameaninglessname** [UnrealisticDev/Renom#9]
I have many plugins that i want to rename, due to the lack of considering naming prefix.

And it looks not possible to do batch operation in current interactive manner. (Anyway, this project is awesome enough, thanks a lot♥!)

**Comment by looterz** [comment]
Having a CLI for renom would be awesome. It's probably a niche use case, but being able to create a script that batch renames a set of modules, targets, etc. without having to manually interact for each one inputting the settings would be useful.

**Comment by msmoiz** [comment]
This is a good idea, will look into implementation.

**Comment by msmoiz** [comment]
This feature has been released with version 1.2.0.
